"""new

Revision ID: 768b03783984
Revises: f96e407bd4af
Create Date: 2023-06-09 08:51:11.824219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '768b03783984'
down_revision = 'f96e407bd4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=99),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=99),
               existing_nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
